name: Contract Tests

on:
  push:
    branches:
      - '**'
    paths:
      - 'test/**'
      - 'contracts/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Change directory
        run: cd hardhat

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Compile contracts
        run: npm run compile

      - name: Run tests
        run: npm run test
