name: Contract Tests

on:
  push:
    branches:
      - '**'
    paths:
      - 'hardhat/test/**'
      - 'hardhat/contracts/**'

  pull_request:
    branches:
      - '**'
    paths:
      - 'hardhat/test/**'
      - 'hardhat/contracts/**'

  workflow_dispatch:

defaults:
  run:
    working-directory: hardhat

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Compile contracts
        run: npm run compile

      - name: Run tests
        run: npm run test
