# This is a basic workflow to help you get started with Actions

name: Deploy React dApp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Compile contracts
        run: |
          cd hardhat
          npm ci --ignore-scripts
          npm run clean
          npm run compile

      - name: Build
        run: |
          cd frontend
          npm ci --ignore-scripts
          npm run build
        env:
          REACT_APP_DEPLOYER_ADDRESS: '0x6E0a4931AF9f11df3c6Fce72454d1d9718C002AC'
          REACT_APP_SWAPPER_ADDRESS: '0x06a61dd7C52F11388e085Eb9b4B7223caE15BBE9'

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./frontend/build
